# Input parameters
SOURCE_DIR=$1
OUTPUT_FILE=$2

# Debugging: Check if source directory exists
echo "Processing source directory: $SOURCE_DIR"

# Ensure the output file is not empty or exists
echo "Generating PlantUML file: $OUTPUT_FILE"
echo "@startuml" > $OUTPUT_FILE
echo "Generated by generate_puml_from_code.sh" >> $OUTPUT_FILE

# Debugging: List files found
echo "Finding C# files in $SOURCE_DIR"
find $SOURCE_DIR -name "*.cs" | while read FILE; do
    echo "Processing file: $FILE"
    
    class_name=$(basename "$FILE" .cs)
    
    # If class_name is empty, skip processing this file
    if [ -z "$class_name" ]; then
        echo "Skipping empty class name for file: $FILE"
        continue
    fi
    
    echo "class $class_name" >> $OUTPUT_FILE
    echo "  +void someMethod()" >> $OUTPUT_FILE  # Placeholder for methods
done

echo "@enduml" >> $OUTPUT_FILE

echo "PlantUML file generated at $OUTPUT_FILE"
