#!/bin/bash

# Input parameters
SOURCE_DIR=$1
OUTPUT_FILE=$2

# Debugging: Check if source directory exists
echo "Processing source directory: $SOURCE_DIR"

# Start generating the PUML file
echo "@startuml" > $OUTPUT_FILE
echo "Generated by generate_puml_from_code.sh" >> $OUTPUT_FILE

# Parse all C# files and extract basic class structures (Example logic)
find $SOURCE_DIR -name "*.cs" | while read FILE; do
    echo "Processing file: $FILE"
    
    # Example logic: Add a class for each C# file (simplified)
    # You can enhance this logic to parse actual C# class structures
    class_name=$(basename "$FILE" .cs)
    echo "class $class_name" >> $OUTPUT_FILE
    echo "  +void someMethod()" >> $OUTPUT_FILE  # Placeholder for methods
done

echo "@enduml" >> $OUTPUT_FILE

echo "PlantUML file generated at $OUTPUT_FILE"
