version: "3.8"

services:
  backend:
    image: mcr.microsoft.com/dotnet/aspnet:8.0 
    container_name: csharp-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5000:80" 
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - frontend

  frontend:
    image: node:18
    container_name: vite-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000" 
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://backend:5000

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
