version: '3.8'

services:
  app:
    image: wpr_project
    build: .
    ports:
      - "5000:80" 
      - "5002:8443" 
    networks:
      - wpr-network
    environment:
      - DB_SERVER=95.99.30.110

networks:
  wpr-network:
    driver: bridge
