version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"  # Backend port mapping (Container port : Host port)
    networks:
      - app-network
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5001"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Frontend development port
    networks:
      - app-network

  nginx:
    build:
      context: .  # Root context for the entire project (this includes frontend, backend, nginx)
    ports:
      - "8080:80"
      - "8443:8443"
    depends_on:
      - frontend
      - backend  # Ensure backend starts before nginx
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/nginx/nginx.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      
    entrypoint: ["nginx", "-g", "daemon off;"] 

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  app-network:
    driver: bridge