version: "3.9"

services:
  # Backend Service
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" 
    env_file:
      - ./backend/.env 
    networks:
      - app-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
    networks:
      - app-network

  # NGINX Reverse Proxy
  nginx:
    build:
      context: . 
    ports:
      - "8080:80"
      - "8443:8443"
    depends_on:
      - frontend
      - backend 
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/nginx/nginx.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      
    entrypoint: ["nginx", "-g", "daemon off;"] 

networks:
  app-network:
    driver: bridge
