version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"  # Backend port mapping (Container port : Host port)
    networks:
      - app-network
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5001"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Frontend development port
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    entrypoint: ["./wait-for-it.sh", "backend:8080", "--", "nginx", "-g", "daemon off;"]

networks:
  app-network:
    driver: bridge
