version: "3.9"

services:
  backend:
    container_name: wpr_backend_1
    build:
      context: .  # The directory where the Dockerfile is located (root of your project)
      dockerfile: Dockerfile  # Specifies the Dockerfile to use
    ports:
      - "5000:5000"  # Expose backend API port
    networks:
      - app-network
    env_file:
      "./backend/.env"

  frontend:
    container_name: wpr_frontend_1
    build:
      context: .  # Build context is the root of your project
      dockerfile: Dockerfile  # Same Dockerfile as backend to build both frontend and backend
    ports:
      - "3000:3000"  # Expose React frontend port
    networks:
      - app-network
    env_file:
      "./frontend/.env"

  nginx:
    container_name: wpr_nginx_1
    image: nginx:alpine  # Use official Nginx image
    build:
      context: .  # Build Nginx from the current directory
    ports:
      - "8080:8080"  # Expose Nginx HTTP port
      - "8443:8443"  # Expose Nginx HTTPS port
    depends_on:
      - frontend
      - backend
    command: ["./wait-for-it.sh", "backend:5000", "--", "nginx", "-g", "daemon off;"]  # Wait for backend before starting Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Nginx configuration file
      - ./nginx/certbot/conf:/etc/letsencrypt  # Certbot files for HTTPS certificates
      - ./nginx/certbot/www:/var/www/certbot  # Certbot webroot directory
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Define custom bridge network for communication between services
