version: '3.9'

services:
  frontend:
    image: your-frontend-image
    ports:
      - "3000:3000"
    networks:
      - app_network

  backend:
    image: your-backend-image
    ports:
      - "5000:5000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
