version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" # Backend is exposed on port 5000
    env_file:
      - ./backend/.env.development
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" # Frontend is exposed on port 3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
