version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"  
    env_file:
      - ./backend/.env
    networks:
      - app-network
    
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"  # Frontend development port
    env_file:
      - ./frontend/.env
    networks:
      - app-network
    

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:8443"
    depends_on:
      - frontend
      - backend  # Ensure backend starts before nginx
    #entrypoint: ["/usr/local/bin/wait-for-it.sh", "backend:5000", "--", "nginx", "-g", "daemon off;"]
    entrypoint: /bin/sh
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/nginx/nginx.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      

  #certbot:
    #image: certbot/certbot
    #volumes:
      #- ./nginx/certbot/conf:/etc/letsencrypt
      #- ./nginx/certbot/www:/var/www/certbot
    #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  app-network:
    driver: bridge