version: "3.9"

services:
  # Backend Service
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" 
    env_file:
      - ./backend/.env 
    networks:
      - app-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
    networks:
      - app-network

  # NGINX Reverse Proxy (Only for Deployment)
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    profiles:
      - production # Only included when `--profile production` is used

networks:
  app-network:
    driver: bridge
