version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_SERVER=${DB_SERVER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CRYPTION_KEY=${CRYPTION_KEY}
      - CRYPTION_IV=${CRYPTION_IV}
      - SALT={SALT}
      - SMTP_HOST={SMTP_HOST}
      - SMTP_PORT={SMTP_PORT}
      - SMTP_FROM_EMAIL={SMTP_FROM_EMAIL}
      - SMTP_FROM_PASSWORD={SMTP_FROM_PASSWORD}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  
      - "80:80" 
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: local