version: '3.9'

services:
  backend:
    image: backend-app
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend/public:/app # Mount the publish folder
    ports:
      - "5000:5000" # Expose backend on port 5000

  frontend:
    image: frontend-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/dist:/usr/share/nginx/html # Serve static files
    ports:
      - "3000:3000" # Expose frontend dev server (optional)

  nginx:
    image: nginx
    ports:
      - "80:80" # Expose Nginx on port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Use custom Nginx config
      - ./frontend/dist:/usr/share/nginx/html # Serve frontend
      - ./backend/publish:/var/www/backend # Proxy requests to backend
