version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_SERVER=${DB_SERVER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CRYPTION_KEY=${CRYPTION_KEY}
      - CRYPTION_IV=${CRYPTION_IV}
      - SALT={SALT}
      - SMTP_HOST={SMTP_HOST}
      - SMTP_PORT={SMTP_PORT}
      - SMTP_FROM_EMAIL={SMTP_FROM_EMAIL}
      - SMTP_FROM_PASSWORD={SMTP_FROM_PASSWORD}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    
  nginx:
    build:
      context: . 
    ports:
      - "8080:80"
      - "8443:8443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  app-network:
    driver: bridge
