version: '3.8'

services:
  app:
    image: wpr_project
    build: .
    ports:
      - "5000:8080" 
      - "5002:8443" 
    networks:
      - wpr-network
    env_file:
      - ./backend/.env

networks:
  wpr-network:
    driver: bridge
