
FROM nginx:alpine

RUN apk update && apk add --no-cache nginx


COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/certbot/conf /etc/letsencrypt
COPY ./nginx/certbot/www /var/www/certbot


EXPOSE 8080 8443

CMD ["nginx", "-g", "daemon off;"]
