version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env 
    networks:
      - app-network
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5000"
      DB_SERVER: ${DB_SERVER}

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      VITE_REACT_APP_BACKEND_URL: "http://backend:5000"

  nginx:
    image: nginx:alpine
    build:
      context: .
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - frontend
      - backend
    #command: ["./wait-for-it.sh", "backend:5000", "--", "nginx", "-g", "daemon off;"]
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot

networks:
  app-network:
    driver: bridge
