version: '2'
 
services:
  app:
    build:
      context:  ./backend
      dockerfile: Dockerfile
    expose:
      - "5000"
 
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "8084:80"
    links:
      - app