version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env  # Backend only
    networks:
      - app-network
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Frontend development port
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    build:
      context: .
    ports:
      - "8080:80"
      - "8443:8443"
    depends_on:
      - frontend
      - backend
    command: ["./wait-for-it.sh", "backend:5000", "--", "nginx", "-g", "daemon off;"]
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/nginx/nginx.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot

networks:
  app-network:
    driver: bridge
