version: "3.9"

services:
  # Backend Service
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"  # Backend port mapping (Container port : Host port)
    env_file:
      - ./backend/.env  # Default for development
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5000"
      #NODE_ENV=${NODE_ENV:-development}  # Default is 'development'
    networks:
      - app-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"   # Frontend development port
      - "8081:8080"   # Change production port to 8081
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL:-http://localhost:5000}
    networks:
      - app-network

  # NGINX Reverse Proxy (Only for Deployment)
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:8080"
      - "8443:8443"  # Production SSL port
    depends_on:
      - frontend
      - backend
    entrypoint: ["./wait-for-it.sh", "backend:8080", "--", "nginx", "-g", "daemon off;"]
    networks:
      - app-network
    profiles:
      - production  # Only included when `--profile production` is used

networks:
  app-network:
    driver: bridge
