version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
