@startuml
class CookieController {
    + CookieController(connector:Connector, userRepository:IUserRepository, crypt:Crypt)
    + <<async>> GetUserId() : Task<IActionResult>
}
ControllerBase <|-- CookieController
CookieController --> "_connector" Connector
CookieController --> "_userRepository" IUserRepository
CookieController --> "_crypt" Crypt
@enduml
