@startuml
class ChangeUserSettingsController {
    + ChangeUserSettingsController(connector:Connector, userRepository:IUserRepository, crypt:Crypt)
    + <<async>> ChangeUserInfoAsync(changeUserRequest:ChangeUserRequest) : Task<IActionResult>
    + <<async>> DeleteUserAsync() : Task<IActionResult>
}
ControllerBase <|-- ChangeUserSettingsController
ChangeUserSettingsController --> "_connector" Connector
ChangeUserSettingsController --> "_userRepository" IUserRepository
ChangeUserSettingsController --> "_crypt" Crypt
@enduml
