@startuml
class ChangeUserRequest {
    + Id : int <<get>> <<set>>
    + Email : string? <<get>> <<set>>
    + Password : string? <<get>> <<set>>
    + FirstName : string? <<get>> <<set>>
    + LastName : string? <<get>> <<set>>
    + TelNum : string <<get>> <<set>>
    + Adres : string? <<get>> <<set>>
}
@enduml
