var change_user_settings_controller_8cs =
[
    [ "WPR.Controllers.ChangeUserSettings.ChangeUserSettingsController", "class_w_p_r_1_1_controllers_1_1_change_user_settings_1_1_change_user_settings_controller.html", "class_w_p_r_1_1_controllers_1_1_change_user_settings_1_1_change_user_settings_controller" ]
];