@startuml
class RentalController {
    + RentalController(connector:Connector, crypt:Crypt, emailService:EmailService, vehicleRepo:VehicleRepository)
    + <<async>> CreateRental(rentalRequest:RentalRequest) : Task<IActionResult>
    + <<async>> GetAllUserRentalsAsync() : Task<IActionResult>
    + <<async>> GetAllUserRentalsWithDetailsAsync() : Task<IActionResult>
}
ControllerBase <|-- RentalController
RentalController --> "_connector" Connector
RentalController --> "_crypt" Crypt
RentalController --> "_emailService" EmailService
RentalController --> "_vehicleRepo" VehicleRepository
@enduml
