@startuml
class SignUpRequest {
    + Email : string? <<get>> <<set>>
    + Password : string? <<get>> <<set>>
    + FirstName : string? <<get>> <<set>>
    + LastName : string? <<get>> <<set>>
    + TelNumber : string <<get>> <<set>>
    + Adres : string? <<get>> <<set>>
    + KvK : int? <<get>> <<set>>
}
SignUpRequest --> "BirthDate" DateTime
@enduml
