@startuml
class EmployeeController {
    + EmployeeController(userRepository:IUserRepository, connector:Connector, crypt:Crypt, sessionHandler:SessionHandler)
    + IsUserEmployee() : Task<bool>
}
ControllerBase <|-- EmployeeController
EmployeeController --> "_userRepository" IUserRepository
EmployeeController --> "_connector" Connector
EmployeeController --> "_sessionHandler" SessionHandler
EmployeeController --> "_crypt" Crypt
@enduml
