@startuml
interface IUserRepository {
    AddVehicleAsync(yop:int, brand:string, type:string, licensPlate:string, color:string, sort:string, price:double, description:string, vehicleBlob:byte[]) : Task<(bool status, string message)>
    AddStaff(personData:Object[]) : Task<(bool status, string message)>
    checkUsageEmailAsync(email:string) : Task<(bool status, string message)>
    GetReviewIdsAsync(user:string, userId:string) : Task<(bool status, List<string> ids)>
    GetReviewAsync(id:string) : Task<(bool status, List<Dictionary<string, object>> data)>
    SetStatusAsync(id:string, status:string, employee:string, userType:string) : Task<(bool status, string message)>
}
@enduml
