@startuml
class UserRepository {
    + UserRepository(connector:Connector, hash:Hash)
    + <<async>> AddVehicleAsync(yop:int, brand:string, type:string, licensePlate:string, color:string, sort:string, price:double, description:string, vehicleBlob:byte[]) : Task<(bool status, string message)>
    + <<async>> AddStaff(personData:Object[]) : Task<(bool status, string message)>
    + <<async>> checkUsageEmailAsync(email:string) : Task<(bool status, string message)>
    - <<async>> GetUserDataAsync(userid:string) : Task<(bool status, Dictionary<string, object> data)>
    - <<async>> GetVehicleData(carId:string) : Task<(bool status, Dictionary<string, object> data)>
    + <<async>> GetReviewIdsAsync(user:string, userId:string) : Task<(bool status, List<string> ids)>
    + <<async>> GetReviewAsync(id:string) : Task<(bool status, List<Dictionary<string, object>> data)>
    - GetKvK(id:string) : string
    + <<async>> SetStatusAsync(id:string, status:string, employee:string, userType:string) : Task<(bool status, string message)>
}
IUserRepository <|-- UserRepository
UserRepository --> "_connector" Connector
UserRepository --> "_hash" Hash
@enduml
