@startuml
interface IConnector {
    CreateDbConnection() : IDbConnection
}
class Connector {
    + Connector(envConfig:EnvConfig)
    + <<virtual>> CreateDbConnection() : IDbConnection
}
IConnector <|-- Connector
Connector --> "_envConfig" EnvConfig
@enduml
