@startuml
class SignUpStaffController {
    + SignUpStaffController(userRepository:IUserRepository)
    + <<async>> SignUpStaff(signUpRequest:SignUpRequest) : Task<IActionResult>
}
ControllerBase <|-- SignUpStaffController
SignUpStaffController --> "_userRepository" IUserRepository
@enduml
