@startuml
!include .\\AppConfigure.puml
!include .\\Program.puml
!include .\\Cryption\crypt.puml
!include .\\Data\EnvConfig.puml
!include .\\Database\Connector.puml
!include .\\Hashing\hash.puml
!include .\\Repository\IUserRepository.puml
!include .\\Repository\IVehicleRepository.puml
!include .\\Repository\UserRepository.puml
!include .\\Repository\VehicleRepository.puml
!include .\\Services\EmailService.puml
!include .\\Utils\BirthdayChecker.puml
!include .\\Utils\EmailChecker.puml
!include .\\Utils\KvkChecker.puml
!include .\\Utils\PasswordChecker.puml
!include .\\Utils\TelChecker.puml
!include .\\Controllers\ChangeUserSettings\changeUserRequest.puml
!include .\\Controllers\ChangeUserSettings\changeUserSettingsController.puml
!include .\\Controllers\Cookie\cookieController.puml
!include .\\Controllers\Cookie\SessionHandler.puml
!include .\\Controllers\Employee\EmployeeController.puml
!include .\\Controllers\Home\homeController.puml
!include .\\Controllers\login\loginController.puml
!include .\\Controllers\login\loginRequest.puml
!include .\\Controllers\Rental\CreateRentalRequest.puml
!include .\\Controllers\Rental\RentalController.puml
!include .\\Controllers\signUp\signUpController.puml
!include .\\Controllers\signUp\signUpRequest.puml
!include .\\Controllers\Vehicle\VehicleController.puml
@enduml
