@startuml
!include .\\AppConfigure.puml
!include .\\Program.puml
!include .\\Cryption\crypt.puml
!include .\\Data\EnvConfig.puml
!include .\\Database\Connector.puml
!include .\\Hashing\hash.puml
!include .\\Repository\IUserRepository.puml
!include .\\Repository\UserRepository.puml
!include .\\Swagger\fileUploadOperationFilter.puml
!include .\\Utils\EmailChecker.puml
!include .\\Utils\PasswordChecker.puml
!include .\\Controllers\acceptHireRequest\acceptHireRequestController.puml
!include .\\Controllers\acceptHireRequest\acceptHireRequestRequest.puml
!include .\\Controllers\acceptHireRequest\hireRequest.puml
!include .\\Controllers\addVehicle\addVehicleController.puml
!include .\\Controllers\addVehicle\addVehicleRequest.puml
!include .\\Controllers\Cookie\cookieController.puml
!include .\\Controllers\signUpStaff\signUpRequest.puml
!include .\\Controllers\signUpStaff\signUpStaffController.puml
!include .\\Controllers\validateUser\validateUserController.puml
@enduml
