@startuml
class SessionHandler {
    - disposedValue : bool
    + CreateCookie(responseCookies:IResponseCookies, cookieName:string, cookieValue:string) : void
    + CreateInvalidCookie(responseCookies:IResponseCookies, cookieName:string) : void
    # <<virtual>> Dispose(disposing:bool) : void
    + Dispose() : void
}
IDisposable <|-- SessionHandler
@enduml
