WPR.Controllers.SignUp.SignUpController Class Reference
SignUpController zorgt ervoor dat persoonlijke en zakelijke accounts aangemaakt kunnen worden.
Public Member Functions
SignUpController (Connector connector, IUserRepository userRepository, EnvConfig envConfig, Hash hash, EmailService emailService)
async Task< IActionResult > signUpPersonalAsync ([FromBody] SignUpRequest signUpRequest)
Een account voor particuliere gebruikers kan aangemaakt worden (onderscheiden door geboortedatum)
async Task< IActionResult > signUpEmployeeAsync ([FromBody] SignUpRequest signUpRequest)
Een account voor zakelijke gebruikers kan aangemaakt worden (onderscheiden door KvK-nummer)
Private Member Functions
bool IsFilledIn (SignUpRequest signUpRequest)
Er wordt gekeken of alle noodzakelijke velden voor het aanmaken van een account ingevuld zijn.
Private Attributes
readonly Connector _connector
readonly IUserRepository _userRepository
readonly EnvConfig _envConfig
readonly Hash _hash
readonly EmailService _emailService
Detailed Description
SignUpController zorgt ervoor dat persoonlijke en zakelijke accounts aangemaakt kunnen worden.
Definition at line 19 of file signUpController.cs.
Constructor & Destructor Documentation
SignUpController()
WPR.Controllers.SignUp.SignUpController.SignUpController (Connector connector, IUserRepository userRepository, EnvConfig envConfig, Hash hash, EmailService emailService) [inline]
Definition at line 27 of file signUpController.cs.
    {
        _connector = connector ?? throw new ArgumentNullException(nameof(connector));
        _userRepository = userRepository ?? throw new ArgumentNullException(nameof(userRepository));
        _envConfig = envConfig ?? throw new ArgumentNullException(nameof(envConfig));
        _hash = hash ?? throw new ArgumentNullException(nameof(hash));
        _emailService = emailService ?? throw new ArgumentNullException(nameof(emailService));
    }
References _connector, _emailService, _envConfig, _hash, and _userRepository.
Member Function Documentation
IsFilledIn()
bool WPR.Controllers.SignUp.SignUpController.IsFilledIn (SignUpRequest signUpRequest) [inline], [private]
Er wordt gekeken of alle noodzakelijke velden voor het aanmaken van een account ingevuld zijn.
Parameters
signUpRequest
Returns
Definition at line 41 of file signUpController.cs.
    {
        return
        !(signUpRequest == null
        || string.IsNullOrEmpty(signUpRequest.Email)
        || string.IsNullOrEmpty(signUpRequest.Password)
        || string.IsNullOrEmpty(signUpRequest.FirstName)
        || string.IsNullOrEmpty(signUpRequest.LastName)
        || string.IsNullOrEmpty(signUpRequest.TelNumber));
    }
References WPR.Controllers.SignUp.SignUpRequest.Email, WPR.Controllers.SignUp.SignUpRequest.FirstName, WPR.Controllers.SignUp.SignUpRequest.LastName, WPR.Controllers.SignUp.SignUpRequest.Password, and WPR.Controllers.SignUp.SignUpRequest.TelNumber.
Referenced by signUpEmployeeAsync(), and signUpPersonalAsync().
signUpEmployeeAsync()
async Task< IActionResult > WPR.Controllers.SignUp.SignUpController.signUpEmployeeAsync ([FromBody] SignUpRequest signUpRequest) [inline]
Een account voor zakelijke gebruikers kan aangemaakt worden (onderscheiden door KvK-nummer)
Parameters
signUpRequest
Returns
Definition at line 183 of file signUpController.cs.
    {
        var connection = _connector.CreateDbConnection();
        var emailCheck = _userRepository.checkUsageEmailAsync(signUpRequest.Email);
        bool commit = true;
        using (var transaction = connection.BeginTransaction())
        {
            try
            {
                // Er wordt gekeken of alle velden zijn ingevuld
                bool filledIn = IsFilledIn(signUpRequest);
                if (!filledIn)
                {
                    return BadRequest(new { message = "Not all elements are filled in" });
                }
                // Er wordt gekeken of het opgegeven emailadress valid is
                if (!EmailChecker.IsValidEmail(signUpRequest.Email))
                {
                    return BadRequest(new { message = "Invalid email format" });
                }
                // er wordt gekeken of het opgegevens KvK nummer in de DataBase staat
                var kvkChecker = new KvkChecker(_userRepository);
                var (isValidKvk, kvkErrorMessage) = await kvkChecker.IsKvkNumberValid(signUpRequest.KvK);
                if (!isValidKvk)
                {
                    return BadRequest(new { message = kvkErrorMessage });
                }
                
                // Er wordt gekeken of het wachtwoord bestaat uit minstens 10 karakters, 1 hoofdletter, 1 kleine letter, 1 cijfer en 1 speciaal teken
                var (isPasswordValid, passwordError) = PasswordChecker.IsValidPassword(signUpRequest.Password);
                if (!isPasswordValid)
                {
                    return BadRequest(new { message = passwordError });
                }
                var emailStatus = await emailCheck;
                // Er wordt gekeken of er een geldig 06-nummer is opgegeven
                if (!TelChecker.IsValidPhoneNumber(signUpRequest.TelNumber))
                {
                    return BadRequest(new { message = "Invalid phone number" });
                }
                else if (emailStatus.status)
                {
                    transaction.Rollback();
                    commit = false;
                    return BadRequest(new { message = "Email already exists"});
                }
                // Als alle velden zijn ingevuld en het KvK nummer is niet leeg, dan wordt er een nieuwe customer aangemaakt
                else if (filledIn && signUpRequest.KvK != null)
                {
                    // Er wordt in de table UserCustomer een gebruiker aangemaakt
                    var customer = await _userRepository.addCustomerAsync(new object[]
                    {
                        signUpRequest.Adres,
                        signUpRequest.TelNumber,
                        _hash.createHash(signUpRequest.Password),
                        signUpRequest.Email,
                        signUpRequest.FirstName,
                        signUpRequest.LastName
                    });
                    // Er wordt aan de nieuw aangemaakt customer het opgegeven KvK nummer gekoppeld in de tabel UserEmployee
                    var employee = await _userRepository.addEmployeeCustomerAsync(new object[]
                    {
                        customer.newUserID,
                        signUpRequest.KvK
                    });
                    // Als het opslaan van de medewerker mislukt wordt te transactie gerollbacked
                    if (!employee.status)
                    {
                        transaction.Rollback();
                        commit = false;
                        return BadRequest(new { employee.status });
                    }
                    // Er wordt een welkomsemail verstuurd
                    await _emailService.SendWelcomeEmail(signUpRequest.Email);
                    return Ok(new { employee.status });
                }
                else
                {
                    return BadRequest(new { message = "Something went wrong (Nothing mathced)" });
                }
            }
            catch (Exception ex)
            {
                transaction.Rollback();
                commit = false;
                
                return StatusCode(500, new
                {
                    message = ex.Message,
                    details = ex.Message,
                    stackTrace = ex.StackTrace
                });
            }
            finally
            {
                if (commit)
                {
                    transaction.Commit();
                }
            }
        }
    }
References _connector, _emailService, _hash, _userRepository, IsFilledIn(), WPR.Utils.EmailChecker.IsValidEmail(), WPR.Utils.PasswordChecker.IsValidPassword(), and WPR.Utils.TelChecker.IsValidPhoneNumber().
signUpPersonalAsync()
async Task< IActionResult > WPR.Controllers.SignUp.SignUpController.signUpPersonalAsync ([FromBody] SignUpRequest signUpRequest) [inline]
Een account voor particuliere gebruikers kan aangemaakt worden (onderscheiden door geboortedatum)
Parameters
signUpRequest
Returns
Definition at line 59 of file signUpController.cs.
    {
        // Het emailadres wordt gecontrolleerd of het emailadres al bestaat
        var emailCheck = _userRepository.checkUsageEmailAsync(signUpRequest.Email);
        bool commit = true;
        using (var connection = _connector.CreateDbConnection())
        using (var transaction = connection.BeginTransaction())
        {
            Console.WriteLine($"Received BirthDate: {signUpRequest.BirthDate}");
            Console.WriteLine($"{signUpRequest.Email} | {signUpRequest.Password} | {signUpRequest.FirstName} | {signUpRequest.LastName} | {signUpRequest.TelNumber} {signUpRequest.Adres} | {signUpRequest.BirthDate}");
            try
            {
                // Er wordt gekeken of alle gegevens ingevuld zijn
                bool filledIn = IsFilledIn(signUpRequest);
                if (!filledIn)
                {
                    return BadRequest(new { message = "Not all elements are filled in" });
                }
                
                // Er wordt gekeken of het opgegeven emailadres valid is
                if (!EmailChecker.IsValidEmail(signUpRequest.Email))
                {
                    return BadRequest(new { message = "Invalid email format" });
                }
                // Er wordt gekeken of er een geldige geboorte datum ingevuld is (niet groter dan 120)
                if (!BirthdayChecker.IsValidBirthday(signUpRequest.BirthDate))
                {
                    return BadRequest(new { message = "Invalid birthday format" });
                }
                // Er wordt gekeken of het ingevoerde telefoonnummer een geldig nederlands nummer is
                if (!TelChecker.IsValidPhoneNumber(signUpRequest.TelNumber))
                {
                    return BadRequest(new { message = "Invalid phone number" });
                }
                
                // Er wordt gekeken of het wachtwoord bestaat uit minstens 10 karakters, 1 hoofdletter, 1 kleine letter, 1 cijfer en 1 speciaal teken
                var (isPasswordValid, passwordError) = PasswordChecker.IsValidPassword(signUpRequest.Password);
                var emailStatus = await emailCheck;
                if (!isPasswordValid)
                {
                    return BadRequest(new { message = passwordError });
                }
                // Als het emailadres al bestaat worden de gegevens gerollbacked
                else if (emailStatus.status)
                {
                    transaction.Rollback();
                    commit = false;
                    return BadRequest(new { message = "Email already exists"});
                }
                // Als alle velden zijn ingevuld en de geboorte datum is ingevuld, wordt er een nieuwe customer aangemaakt
                else if (filledIn && signUpRequest.BirthDate != null)
                {
                    // Er wordt een nieuwe gebruiker aangemaakt in de tabel UserCustomer
                    var customer = await _userRepository.addCustomerAsync(new object[]
                    {
                        signUpRequest.Adres,
                        signUpRequest.TelNumber,
                        _hash.createHash(signUpRequest.Password),
                        signUpRequest.Email,
                        signUpRequest.FirstName,
                        signUpRequest.LastName
                    });
                    // Er wordt aan de nieuwe customer het opgegeven geboortedatum gekoppeld in de tabel UserPersonal
                    var personal = await _userRepository.addPersonalCustomerAsync(new object[]
                    {
                        customer.newUserID,
                        signUpRequest.BirthDate
                    });
                    // Als het koppelen mislukt wordt de transactie geroldbacked
                    if (!personal.status)
                    {
                        transaction.Rollback();
                        commit = false;
                        return BadRequest(new { personal.message });
                    }
                    // Er wordt een welkomsemail verstuurd
                    await _emailService.SendWelcomeEmail(signUpRequest.Email);
                    
                    return Ok(new { message = "Account created successfully. Please check your email to confirm your account" });
                }
                else
                {
                    return BadRequest(new { message = "Something went wrong (Nothing matched)" });
                }
            }
            catch (Exception ex)
            {
                transaction.Rollback();
                commit = false;
                return StatusCode(500, new
                {
                    message = ex.Message,
                    details = ex.Message,
                    stackTrace = ex.StackTrace
                });
            }
            finally
            {
                if (commit)
                {
                    transaction.Commit();
                }
            }
        }
    }
References _connector, _emailService, _hash, _userRepository, IsFilledIn(), WPR.Utils.BirthdayChecker.IsValidBirthday(), WPR.Utils.EmailChecker.IsValidEmail(), WPR.Utils.PasswordChecker.IsValidPassword(), and WPR.Utils.TelChecker.IsValidPhoneNumber().
Field Documentation
_connector
readonly Connector WPR.Controllers.SignUp.SignUpController._connector [private]
Definition at line 21 of file signUpController.cs.
Referenced by SignUpController(), signUpEmployeeAsync(), and signUpPersonalAsync().
_emailService
readonly EmailService WPR.Controllers.SignUp.SignUpController._emailService [private]
Definition at line 25 of file signUpController.cs.
Referenced by SignUpController(), signUpEmployeeAsync(), and signUpPersonalAsync().
_envConfig
readonly EnvConfig WPR.Controllers.SignUp.SignUpController._envConfig [private]
Definition at line 23 of file signUpController.cs.
Referenced by SignUpController().
_hash
readonly Hash WPR.Controllers.SignUp.SignUpController._hash [private]
Definition at line 24 of file signUpController.cs.
Referenced by SignUpController(), signUpEmployeeAsync(), and signUpPersonalAsync().
_userRepository
readonly IUserRepository WPR.Controllers.SignUp.SignUpController._userRepository [private]
Definition at line 22 of file signUpController.cs.
Referenced by SignUpController(), signUpEmployeeAsync(), and signUpPersonalAsync().
The documentation for this class was generated from the following file:
D:/codes/WPR/backend/src/Controllers/signUp/signUpController.cs