WPR.Data.EnvConfig Class Reference
Leez het .env bestand uit waarin de connectie strings staan naar de database. Deze staan in een apart bestand buiten de git repo, zodat mensen van buiten niet met de database kunnen verbinden.
Public Member Functions
EnvConfig ()
virtual string Get (string key)
Haalt de value van de specifieke environement variabelen.
virtual bool IsConfigured ()
Check om te kijken of alle environment variabelen geconfigureerd zijn.
string GetSmtpHost ()
int GetSmtpPort ()
string GetFromEmail ()
string GetFromPassword ()
Private Attributes
readonly IConfiguration _configuration
Detailed Description
Leez het .env bestand uit waarin de connectie strings staan naar de database. Deze staan in een apart bestand buiten de git repo, zodat mensen van buiten niet met de database kunnen verbinden.
Definition at line 12 of file EnvConfig.cs.
Constructor & Destructor Documentation
EnvConfig()
WPR.Data.EnvConfig.EnvConfig () [inline]
Definition at line 16 of file EnvConfig.cs.
    {
        DotEnv.Load(); // Gebruikt de dotenv.net library om het bestand te laden
        var builder = new ConfigurationBuilder()
            .AddEnvironmentVariables(); // Voegt de environment variabelen aan de ConfigurationBuilder
        
        _configuration = builder.Build(); // Bouwt het configuratie object
    }
References _configuration.
Member Function Documentation
Get()
virtual string WPR.Data.EnvConfig.Get (string key) [inline], [virtual]
Haalt de value van de specifieke environement variabelen.
Parameters
key Ophalen environment variabele key.
Returns
De value van de specifieke environment variabele, of null als niet gevonden.
Definition at line 31 of file EnvConfig.cs.
    {
        var value = _configuration[key]; // Fetch de value van de gegeven key
        if (string.IsNullOrEmpty(value))
        {
            Console.WriteLine($"Warning {key} not found in environment");
        }
        return value;
    }
References _configuration.
Referenced by WPR.Hashing.Hash.Hash(), and IsConfigured().
GetFromEmail()
string WPR.Data.EnvConfig.GetFromEmail ()
GetFromPassword()
string WPR.Data.EnvConfig.GetFromPassword ()
GetSmtpHost()
string WPR.Data.EnvConfig.GetSmtpHost ()
GetSmtpPort()
int WPR.Data.EnvConfig.GetSmtpPort ()
IsConfigured()
virtual bool WPR.Data.EnvConfig.IsConfigured () [inline], [virtual]
Check om te kijken of alle environment variabelen geconfigureerd zijn.
Returns
True als alle keys present zijn, anders False.
Definition at line 45 of file EnvConfig.cs.
    {
        var requiredKeys = new[] { "DB_SERVER", "DB_DATABASE", "DB_USERNAME", "DB_PASSWORD" };
        return requiredKeys.All(key => !string.IsNullOrEmpty(Get(key)));
    }
References Get().
Field Documentation
_configuration
readonly IConfiguration WPR.Data.EnvConfig._configuration [private]
Definition at line 14 of file EnvConfig.cs.
Referenced by EnvConfig(), and Get().
The documentation for this class was generated from the following file:
D:/codes/WPR/backend/src/Data/EnvConfig.cs