name: Continuous Integration with Merge Blocker and Auto-Merge

on:
  push:
    branches:
      - '*' 
  pull_request:
    branches:
      - '*' 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test (${ matrix.os }, ${ matrix.configuration })
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        configuration: [Debug, Release]
    timeout-minutes: 30

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore WPR.sln --configuration ${{ matrix.configuration }}

      - name: Run tests
        run: dotnet test --configuration ${{ matrix.configuration }} --no-restore --logger "trx;LogFileName=test-results.trx"

  merge_blocker:
    name: Block Merge if Tests Fail or Auto-Merge if Pass
    runs-on: ubuntu-latest
    needs: build
    if: always() 

    steps:
      - name: Check if tests passed and block merge if needed
        run: |
          echo "Build status: ${{ needs.build.result }}"
          if [[ "${{ needs.build.result }}" != "success" ]]; then
            echo "Tests did not pass, merge blocked."
            exit 1
          else
            echo "Tests passed successfully. Merge is allowed."
            # Automatically merge the pull request if tests pass
            curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d '{"commit_title":"Auto merge by GitHub Actions","commit_message":"Merging automatically after tests passed"}' \
              "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge"
          fi
