name: Auto-Generate UML Diagrams

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  generate_uml:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install dependencies (PlantUML)
      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml

      # Step 3: Ensure the generate_puml_from_code.sh script is executable
      - name: Make generate_puml_from_code.sh executable
        run: chmod +x ./UML/scripts/generate_puml_from_code.sh

      # Step 4: Generate PUML files for Backend and EmployeeBackend
      - name: Generate PUML files
        run: |
          mkdir -p UML/Backend
          mkdir -p UML/BackendEmployee
          ./UML/scripts/generate_puml_from_code.sh ./backend/src UML/Backend/backend.puml
          ./UML/scripts/generate_puml_from_code.sh ./employeeBackend/src UML/BackendEmployee/employeeBackend.puml

      # Step 5: Debugging: Check file encoding and hidden characters
      - name: Check file encoding and hidden characters (backend.puml)
        run: |
          file -i UML/Backend/backend.puml
          cat -A UML/Backend/backend.puml

      - name: Check file encoding and hidden characters (employeeBackend.puml)
        run: |
          file -i UML/BackendEmployee/employeeBackend.puml
          cat -A UML/BackendEmployee/employeeBackend.puml

      # Step 6: Debugging: Print PlantUML version
      - name: Print PlantUML version
        run: java -jar plantuml.jar -version

      # Step 7: Debugging: Ensure Java version is compatible
      - name: Check Java version
        run: java -version

      # Step 8: Simplify the backend.puml file for testing
      - name: Simplify backend.puml for debugging
        run: |
          echo "@startuml" > UML/Backend/backend_simplified.puml
          echo "class TestClass { +void testMethod() }" >> UML/Backend/backend_simplified.puml
          echo "@enduml" >> UML/Backend/backend_simplified.puml

      # Step 9: Generate UML Diagrams using PlantUML (with simplified file for debugging)
      - name: Generate UML Diagrams (debugging step)
        run: |
          java -jar plantuml.jar UML/Backend/backend_simplified.puml

      # Step 10: Upload UML Diagrams as Artifacts (for further analysis)
      - name: Upload UML Diagrams as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: uml-diagrams
          path: |
            UML/Backend/backend_simplified.png
            UML/BackendEmployee/employeeBackend.png
