name: UML Diagram Generation

on:
  workflow_run:
    workflows: ["Continuous Integration with Merge Blocker"]
    types:
      - completed

jobs:
  generate_uml:
    name: Generate UML Diagrams
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Run only if CI workflow succeeded
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PlantUML via downloading the jar
        run: |
          echo "Removing any previous PlantUML JAR if it exists"
          rm -f plantuml.jar
          curl -L https://github.com/plantuml/plantuml/releases/download/v1.2024.8/plantuml-1.2024.8.jar -o plantuml.jar
          # Check if the file exists and is not corrupt
          if [ ! -f plantuml.jar ]; then
            echo "Error: PlantUML JAR file not found"
            exit 1
          fi
          echo "Successfully downloaded PlantUML JAR file"

      - name: Generate UML Diagrams
        run: |
            echo "Running PlantUML for backend.puml..."
            java -jar plantuml.jar UML/Backend/backend.puml
            echo "Running PlantUML for employeeBackend.puml..."
            java -jar plantuml.jar UML/BackendEmployee/employeeBackend.puml

      - name: Upload UML Diagrams as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: uml-diagrams
          path: |
            UML/Backend/backend.png
            UML/BackendEmployee/employeeBackend.png
