name: Auto-Generate UML Diagrams

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  generate_uml:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install dependencies (PlantUML)
      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml

      # Step 3: Ensure the generate_puml_from_code.sh script is executable
      - name: Make generate_puml_from_code.sh executable
        run: chmod +x ./UML/scripts/generate_puml_from_code.sh

      # Step 4: Generate PUML files for Backend and EmployeeBackend
      - name: Generate PUML files
        run: |
          mkdir -p UML/Backend
          mkdir -p UML/BackendEmployee
          ./UML/scripts/generate_puml_from_code.sh ./backend/src UML/Backend/backend.puml
          ./UML/scripts/generate_puml_from_code.sh ./employeeBackend/src UML/BackendEmployee/employeeBackend.puml

      # Step 5: Output the generated PUML files (Debugging step)
      - name: Output PUML files (Debugging)
        run: |
          echo "Contents of backend.puml:"
          cat UML/Backend/backend.puml
          echo "Contents of employeeBackend.puml:"
          cat UML/BackendEmployee/employeeBackend.puml

      # Step 6: Generate UML diagrams using PlantUML
      - name: Generate UML Diagrams
        run: |
          plantuml UML/Backend/backend.puml
          plantuml UML/BackendEmployee/employeeBackend.puml

      # Step 7: Upload UML Diagrams as Artifacts
      - name: Upload UML Diagrams as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: uml-diagrams
          path: |
            UML/Backend/backend.png
            UML/BackendEmployee/employeeBackend.png
