name: Auto-Generate UML Diagrams

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  generate_uml:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install dependencies (PlantUML)
      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml

      # Step 3: Generate PUML files for Backend and EmployeeBackend
      - name: Generate PUML files
        run: |
          mkdir -p UML/Backend
          mkdir -p UML/BackendEmployee
          ./generate_puml_from_code.sh ./backend/src UML/Backend/backend.puml
          ./generate_puml_from_code.sh ./employeeBackend/src UML/BackendEmployee/employeeBackend.puml

      # Step 4: Generate UML diagrams using PlantUML
      - name: Generate UML Diagrams
        run: |
          plantuml UML/Backend/backend.puml
          plantuml UML/BackendEmployee/employeeBackend.puml

      # Step 5: Upload UML Diagrams as Artifacts
      - name: Upload UML Diagrams as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: uml-diagrams
          path: |
            UML/Backend/backend.png
            UML/BackendEmployee/employeeBackend.png
