@startuml
class EmailService {
    + EmailService(envConfig:EnvConfig)
    - CreateSmtpClient() : SmtpClient
    + <<async>> SendWelcomeEmail(toEmail:string) : Task
    + <<async>> SendRentalConfirmMail(toEmail:string, carName:string, carColor:string, carPlate:string, startDate:DateTime, endDate:DateTime, price:string) : Task
    - BuildRentalConfirmationBody(carName:string, carColor:string, carPlate:string, startDate:DateTime, endDate:DateTime, price:string) : string
}
EmailService --> "_envConfig" EnvConfig
@enduml
